### ISSUE TITLE
Investigate DAO vs Repository Pattern

### ISSUE THREAD

**Issue by rafaelfsilva** [ORNL/zambeze#106]
DAO vs repository pattern (https://www.baeldung.com/java-dao-vs-repository)

DAO seems very Java-based, while most Python projects are using SQLAlchemy. We need to investigate whether we should migrate to SQLAlchemy.

**Comment by renan-souza** [comment]
@rafaelfsilva While we can still investigate the repository pattern, DAO is a software design pattern agnostic of any programming language, so I disagree that it is Java-based, even though I understand it become popular in Java projects, as many other software design patterns. But I myself have worked on multiple Python projects, using multiple database models (including NoSQL databases), that are heavily based on DAO abstractions. Some of these projects had to manipulate dozens of persistent object collections. I am quite familiar with i, I think it's a nice pattern, and I've had good experience with it in large-scale Python projects.

Btw, in Zambeze, we are encapsulating the SQL queries in the code in a separate Python file (https://github.com/ORNL/zambeze/blob/devel/zambeze/orchestration/db/dao/dao_utils.py) and we are using SQLAlchemy to query the database. We're just not using SQLAlchemy's ORM and some of its other abstractions.

To me, it is must easier and faster to develop and maintain in this way. But I believe it's a matter of opinion and previous background experience. Since we already have that working in the code and I can volunteer to be the point of contact for the database accesses in Zambeze, I would vote to keep it as is. If you prefer to change to SQLAlchemy ORM patterns, I'm not against it, it will just take me much more time refactor the code and apply these patterns.

**Comment by renan-souza** [comment]
Closing as requested by Rafael.
